//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.14 at 02:53:25 AM EST 
//


package jaxbconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="parameters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="border" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shape" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="predatorStarve" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="predatorBreed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="preyBreed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="probabilityCatch" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stateMatrix">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "jaxbconfiguration")
public class Jaxbconfiguration {

    @XmlElement(required = true)
    protected Jaxbconfiguration.Parameters parameters;
    @XmlElement(required = true)
    protected Jaxbconfiguration.StateMatrix stateMatrix;

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Jaxbconfiguration.Parameters }
     *     
     */
    public Jaxbconfiguration.Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jaxbconfiguration.Parameters }
     *     
     */
    public void setParameters(Jaxbconfiguration.Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the stateMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link Jaxbconfiguration.StateMatrix }
     *     
     */
    public Jaxbconfiguration.StateMatrix getStateMatrix() {
        return stateMatrix;
    }

    /**
     * Sets the value of the stateMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jaxbconfiguration.StateMatrix }
     *     
     */
    public void setStateMatrix(Jaxbconfiguration.StateMatrix value) {
        this.stateMatrix = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="border" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shape" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="predatorStarve" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="predatorBreed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="preyBreed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="probabilityCatch" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Parameters {

        @XmlElement(required = true)
        protected String border;
        @XmlElement(required = true)
        protected String shape;
        @XmlElement(required = true)
        protected String name;
        protected int width;
        protected int height;
        protected int predatorStarve;
        protected int predatorBreed;
        protected int preyBreed;
        protected double probabilityCatch;
        protected double threshold;

        /**
         * Gets the value of the border property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBorder() {
            return border;
        }

        /**
         * Sets the value of the border property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBorder(String value) {
            this.border = value;
        }

        /**
         * Gets the value of the shape property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShape() {
            return shape;
        }

        /**
         * Sets the value of the shape property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShape(String value) {
            this.shape = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the width property.
         * 
         */
        public int getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(int value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public int getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHeight(int value) {
            this.height = value;
        }

        /**
         * Gets the value of the predatorStarve property.
         * 
         */
        public int getPredatorStarve() {
            return predatorStarve;
        }

        /**
         * Sets the value of the predatorStarve property.
         * 
         */
        public void setPredatorStarve(int value) {
            this.predatorStarve = value;
        }

        /**
         * Gets the value of the predatorBreed property.
         * 
         */
        public int getPredatorBreed() {
            return predatorBreed;
        }

        /**
         * Sets the value of the predatorBreed property.
         * 
         */
        public void setPredatorBreed(int value) {
            this.predatorBreed = value;
        }

        /**
         * Gets the value of the preyBreed property.
         * 
         */
        public int getPreyBreed() {
            return preyBreed;
        }

        /**
         * Sets the value of the preyBreed property.
         * 
         */
        public void setPreyBreed(int value) {
            this.preyBreed = value;
        }

        /**
         * Gets the value of the probabilityCatch property.
         * 
         */
        public double getProbabilityCatch() {
            return probabilityCatch;
        }

        /**
         * Sets the value of the probabilityCatch property.
         * 
         */
        public void setProbabilityCatch(double value) {
            this.probabilityCatch = value;
        }

        /**
         * Gets the value of the threshold property.
         * 
         */
        public double getThreshold() {
            return threshold;
        }

        /**
         * Sets the value of the threshold property.
         * 
         */
        public void setThreshold(double value) {
            this.threshold = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "state"
    })
    public static class StateMatrix {

        @XmlElement(required = true)
        protected List<String> state;

        /**
         * Gets the value of the state property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the state property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getState().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getState() {
            if (state == null) {
                state = new ArrayList<String>();
            }
            return this.state;
        }

    }

}
